### ISSUE TITLE
A question on maxCT with covariate

### ISSUE THREAD

**Issue by wongck-kevin** [privefl/bigsnpr#127]
Hi Florian,

I used a sightly modified version of your maxCT code to include a covariate in the model, with something like:

```
grid2$auc <- big_apply(multi_PRS, a.FUN = function(X, ind, s, fam_train) {
  # Sum over all chromosomes, for the same C+T parameters
  single_PRS <- rowSums(X[, ind + s * (0:21)])
  df <- data.frame(fam_train, single_PRS)
  mod <- glm(y ~ covar + single_PRS, data = df, family = "binomial")
  bigstatsr::AUC(mod$fitted.values, df$y)
}, ind = 1:s, s = s, fam_train = fam_train,
a.combine = 'c', block.size = 1, ncores = NCORES)
```
Then I found the number of SNPs in the final model with maxCT is 1. This is because the best p-value threshold was found to be largest value of `grid.lpS.thr`. Since we have multiplied `0.9999` to make this sequence of thresholds, I guess the SNP left is the one with `max(lpval)`. So basically, does it mean the final model in this case is just the covariate itself? I just felt a little strange when I saw 200,000 SNPs are used in the final model with SCT but only 1 (or 0 indeed?) SNP in the final model with maxCT.

**Comment by privefl** [comment]
If you use covariates, I would recommend to use the Z-Score from `glm()` instead of the AUC from the fitted values.

I think you have one very big effect in the GWAS.
SCT just averages models with potentially more variants so you end up with much more variants.
It you are interested in SCT, you might want to try the new parameter `power_adaptive` from `big_sp***Reg()`/`snp_grid_stacking()` (you would need the dev version `remotes::install_github("privefl/bigstatsr@multipf3")`).
If you try e.g. values `c(0, 0.5, 1.5)`, you might end up with much less variables in the `1.5` model.

**Comment by wongck-kevin** [comment]
Hi Florian,

Thanks very much for the suggestion.
The `1.5` model ends up with ~210,000 SNPs while the model without `power_adaptive` has ~220,000 SNPs.

I think I am in a situation that even the best C+T score cannot improve the AUC, and the optimal linear combination of C+T scores can improve the AUC just a tiny bit with a lot of SNPs. By improving the AUC, I mean getting a larger AUC than the model that includes the covarite only.

**Comment by privefl** [comment]
Ok, thanks for trying.

**Comment by wongck-kevin** [comment]
Hi Florian,
I have tested another dataset, but this time without any covarites.
The best C+T predictions provides an AUC of 0.508 [1 SNP] whereas stacking provides an AUC of 0.510 [60,000 SNPs].
I was wondering if you have similar results before (especially just 1 SNP in best C+T) when analyzing GWAS data with possibly no real effects (instead of one very big effect)? Sorry if my question caused any confusion.
