### ISSUE TITLE
Further pruning using snp_autoSVD( ) on previously pruned data

### ISSUE THREAD

**Issue by bweedop** [privefl/bigsnpr#15]
I am running the snp_autoSVD function on a set of SNPs and then once again on a subsequent subset of SNPs afterward. After the pruning and removal of long-range LD regions, I ran the same function on randomly selected subsets (10K SNPs and 50K SNPs) of the already pruned set of SNPs and both are pruned even further, reduced down to a set of ~6K SNPs and ~28K SNPs. 

I am wondering what is happening and I am hoping that you could shed some light on if snp_autoSVD() might come into play here. Why would a subset of the pruned SNPs be pruned even further?

**Comment by privefl** [comment]
What king of data is that? What is the size?
Does the PCs scores really change ?
What do the loadings look like?

**Comment by DrK-Lo** [comment]
Hi Florian,
We have a set of ~3million SNPs from the Eastern Oyster Genome (90 individuals collected across the range). When we run snp_autoSVD, it thins based on clumping and on 11 long-range LD regions, which results in ~400K SNPs. We were interested in using a smaller set of SNPs for estimating structure, so we took a subset (either 10k or 50K) SNPs from the 400K thinned set and ran snp_autoSVD on those sets again. What surprised me is that these subsets were further thinned (based on clumping, but no long-range LD regions were detected) as Bodie described above. The scores change, but mostly because of the way the PC axes were estimated (e.g. PC1 in the 400K snp set had similar scores to PC2 in the smaller SNP sets). I haven't looked at the loadings yet. 
Anyway its not necessarily an "issue", we were just interested in getting some more information on how snp_autoSVD() worked.

**Comment by privefl** [comment]
All the defaults are for e.g. a human chip of 500K SNPs.
Parameter `size` is the number of SNPs by default (radius), so you should probably take a larger value if you have 3M SNPs. You can use physical distance instead in `snp_clumping()` but not in `snp_autoSVD()`.

`LRLDR <- LD.wiki34[0, 1:3]` is just a way to create a data frame with 0 rows but the columns I want.

It is always useful to look at the loadings, you will see quickly if you're capturing e.g. LD structure instead of population structure (you'll get huge peaks). It is better to have normal loadings (without peaks). This and function `snp_autoSVD()` are explained in the paper, if I remember correctly.

Tell me if you have other questions or if I missed some of your questions.

**Comment by DrK-Lo** [comment]
Gotcha. Thanks Florian!


On Oct 9, 2018, at 2:39 PM, Florian Privé <notifications@github.com<mailto:notifications@github.com>> wrote:


All the defaults are for e.g. a human chip of 500K SNPs.
Parameter size is the number of SNPs by default (radius), so you should probably take a larger value if you have 3M SNPs. You can use physical distance instead in snp_clumping() but not in snp_autoSVD().

LRLDR <- LD.wiki34[0, 1:3] is just a way to create a data frame with 0 rows but the columns I want.

It is always useful to look at the loadings, you will see quickly if you're capturing e.g. LD structure instead of population structure (you'll get huge peaks). It is better to have normal loadings (without peaks). This and function snp_autoSVD() are explained in the paper, if I remember correctly.

Tell me if you have other questions or if I missed some of your questions.

**Comment by bweedop** [comment]
Hey Florian. In order to still use snp_autoSVD, I cloned your package and altered the arguments in the function to include the option of using the physical distance window rather than the number of adjacent SNPS. You can take a look at what I changed here; Can think of any issues this would cause? Also, while this is a minor change, I can push this change if you'd like to add this functionality.

` snp_autoSVD <- function(G,
                        infos.chr,
                        infos.pos,
                        ind.row = rows_along(G),
                        ind.col = cols_along(G),
                        fun.scaling = snp_scaleBinom(),
                        thr.r2 = 0.2,
                        size = 500,
                        k = 10,
                        roll.size = 50,
                        int.min.size = 20,
                        is.size.in.bp = FALSE
                        ncores = 1,
                        verbose = TRUE) {

  check_args()

  # Verbose?
  printf2 <- function(...) if (verbose) printf(...)

  # First clumping
  THR <- thr.r2
  printf2("Phase of clumping at r2 > %s.. ", THR)
  ind.keep <- snp_clumping(G, 
                           infos.chr = infos.chr, 
                           ind.row = ind.row,
                           exclude = setdiff(cols_along(G), ind.col),
                           thr.r2 = THR,
                           size = size,
                           is.size.in.bp = is.size.in.bp,
                           infos.pos = infos.pos,
                           ncores = ncores) `

**Comment by privefl** [comment]
When I made this function, my thoughts were:
- this function has already too many arguments to play with
- this function could be useful for non-human data because there is no table of long-range LD available (but sometimes, with these data, you don't have anu information about physical position).
- there is somehow a monotonic transformation between physical distance and number of SNPs. 

So, I'm not sure I want to add two more parameters to this function. Wouldn't it be sufficient to increase parameter `size` for your needs?

**Comment by privefl** [comment]
Finally, I might make this change. 
I'll combine it with other changes to this function.
And I'll provide one version that will work even if you have no information on chromosomes and physical positions.

**Comment by bweedop** [comment]
That would be great! I can understand your reasons for not putting it in originally but with you adding this option makes my life simpler. I'll be interested to see the version that needs no chromosome or position info. Thank you!

**Comment by privefl** [comment]
You can try using `devtools::install_github("privefl/bigsnpr@newautosvd")`.
- I've added parameter `is.size.in.bp`. 
- I now use a Bonferroni-corrected threshold on p-values rather than Tukey's rule (this detects less outliers, allowing the use of `roll.size = 0`, useful when SNPs are not ordered).

I will test this more before merging it in the master branch.
Please send me feedback too.

**Comment by privefl** [comment]
This has been merged in master (#16).

**Comment by bweedop** [comment]
This is fantastic, Florian! Thank you so much! I'll let you know how it goes.
