### ISSUE TITLE
Make use of memory with `snp_fastImpute()`

### ISSUE THREAD

**Issue by suensummit** [privefl/bigsnpr#153]
How to increase the usage of memory while running `snp_fastImpute()` with filebacked FBM?

**Comment by privefl** [comment]
I am not sure what you mean?

**Comment by suensummit** [comment]
I would like to know is it possible to load the whole FBM into memory while compute imputation with `snp_fastImpute()`? As my machine could have up to hundreds GB RAM.

**Comment by privefl** [comment]
No, it should not use much memory because only one variant is processed at once (using only nearby variants).

**Comment by suensummit** [comment]
Hmmm I see, then is there a way to load the data into memory first (as FBM, or I might need to modify the package with native matrix) to save the time of disk I/O? It seems the calculation is sequential instead of parallel and did not speed up much even I use `parallel::parLapply` to impute them in parallel.

**Comment by privefl** [comment]
The disk is accessed from only once. This should be some minimal timing compared to the actual computation.
The parallelism is passed directly to {xgboost}. I've decided not to parallel chromosomes anymore instead because their lengths is so different.
What did you try to parallelize using `parallel::parLapply()`?
Also, what is the size of the data you're trying to impute?

**Comment by suensummit** [comment]
I simply did [this](https://github.com/suensummit/bigsnpr/blob/dev/R/impute.R#L154-L157) trying to parallel the internal function `bigsnpr:::imputeChr`, but it shows no significant speed up.
The dataset I'm working with is a divided one, which contains 100k columns with 5k rows; but the real dataset will have 10M columns with 500k rows.

**Comment by privefl** [comment]
First, if you parallelize the for loop, then you should not use a second level of parallelism inside for xgboost.
Unless, you have access to many nodes on a HPC cluster and you shoud use {future.batchtools} and {future.apply} instead.

Also, instead of using the chromosome subdivision, you could use a smaller division (more splits with less variants).

Is it UKBB data? Why not using the imputed BGEN data directly? I remember having imputed UKBB for 600K variants and it took something like 2-3 days. If you really want to impute 10M variants using {xgboost}, you will need to divide this to many cores.

Tell me if you need more help than the instructions I just gave you to implement this.

**Comment by suensummit** [comment]
I'm planning to run the imputation process on several VMs (could up to hundreds) from cloud services, so the naive way is to divide data. But the problem is that for each individual machine the CPU & memory usage only achieve around 15% of resources, which is a waste of resource in my case...

**Comment by privefl** [comment]
You can always divide in more smaller parts with less memory/CPU each, right?

**Comment by suensummit** [comment]
Yes and it will be an optimisation problem instead. So the computation resource for each single machine seems to be capped/upper-bounded right?

**Comment by privefl** [comment]
As I said before, the memory should not be extremely large if I remember correctly.
And the CPU usage will depend on how good the parallelization is in xgboost.
You could allocate something like 4 cores per task, where each task is processing one block of the data.
Try not to have blocks overlapping chromosomes if you want to maximize prediction at the chromosome ends.

**Comment by suensummit** [comment]
OK, thanks for your advise, I will try in this setting and see whether the performance is better or not. 
And the parallelization in xgboost is controlled by the `nthread` parameter right? Do you have some advises on tuning this? Thanks.

**Comment by suensummit** [comment]
And another question is that what is the difference in computation time between BGEN data and bkfile/RDS data?

**Comment by privefl** [comment]
No, I don't know what would be the best value to use for ncores. I designed this function 3y ago and I've not used it really since then because I'm now working primarily with UK Biobank data where I can read directly from the imputed BGEN files.

What do you mean exactly by difference in computation time with BGEN and my format? The BGEN format is really nice for storing very large datasets. But when you need to access one variable, you need to uncompress it first, which takes a bit of time. In bigstatsr/bigsnpr, I prefer to work with a more simple matrix format on disk.

**Comment by suensummit** [comment]
Oh I got it, I was misunderstood that you are talking about *imputed* BGEN data, I thought you meant that using BGEN data to impute will be faster than BK/RDS files.
And yes, the best value to use for ncores will be an optimisation problem we need to tackle in our task.

**Comment by privefl** [comment]
Closing for now. Feel free to reopen if you have more questions.
