### ISSUE TITLE
Does snp_readBed() read in memory?

### ISSUE THREAD

**Issue by sariya** [privefl/bigsnpr#162]
Hi, 

Thank you for this library. It is amazing to see these helpful functionalities in it.

I had questions for `snp_readBed`: are the plink file loaded completely in this function in the memory or is it indexed?

2- Is there a way I can specify which SNP/regions/boundaries to read from the plink format?

Thank you.

**Comment by privefl** [comment]
- `snp_readBed()` reads the `.bed` file (and writes to the corresponding `.bk` file) byte per byte in order.
- `snp_readBed2()` memory-maps the file and enable accessing a subset of the data (and read in parallel).

None of these two functions should read the whole data in memory at once, and should work fine even though you do not have lots of RAM available.

**Comment by sariya** [comment]
Thank you this is really helpful. 

I can select SNPs as:

  
```
     bedfile <- system.file("extdata", "example.bed", package = "bigsnpr")

   rds <- snp_readBed2(bedfile, backingfile = tempfile(), ind.col=(c(1:4)))

```

**Comment by privefl** [comment]
Yes

**Comment by JasmRicard** [comment]
Hi Florian,
I am actually struggling to read a whole Plink file (1.5M SNPs for 400 000 ind) : R just doesn't seem to do it. As I read your answer: 'None of these two functions should read the whole data in memory at once, and they should work fine even though you do not have lots of RAM available.', it was so much clearer for me. I understand that I should read the Plink file by subsets with snp_readBed2. Is it more efficient to subset by columns of by rows? I'm then wondering if there's a way to merge the resulting bigSNP objects in order to use LDpred2?
Thank you so much for your time.

**Comment by privefl** [comment]
You should be fine reading even this size.
I've once read 450K x 8M from BGEN files (bed should be easier).
What do you mean exactly by "struggling" then?

Another benefit of `snp_readBed2()` is that you can use parallelism, which should be much faster.

**Comment by JasmRicard** [comment]
Thank you for your answer. 
It's a surprise to me! Maybe this can help. It is the message my console keep giving me. I use snp_readBed2() with 6 cores, and the error is the same using only 1 core. If I try using the function on a subset (400 ind for 20 000 SNPs), it's doing ok.
<img width="945" alt="Erreur - snp_readBed - 2" src="https://user-images.githubusercontent.com/78285923/108848051-802b1b00-75ae-11eb-8409-8ce2f45ae55a.PNG">

**Comment by privefl** [comment]
Do you have enough disk space?
