### ISSUE TITLE
LDpred2 RAM requirements?

### ISSUE THREAD

**Issue by mkelcb** [privefl/bigsnpr#172]
I ran several LDpred2 jobs genome-wide on a Hapmap3 panel of SNPs, each with 30 cores and 6GB RAM. The majority of them did not finish within 48 hours. A few of them did, but the rest of them just hanged and got eventually killed by the job scheduler. I've just re-submitted them with requesting 30GB of RAM for each. Checking the live RAM usage, LDpred2 is now using ~22GB RAM. What is worrying is that LDpred2 did not complain before when it only had access to 6GB of RAM, I am guessing that it just ran that much slower, perhaps relying more on reading from the disk?

Could you give us some guidance on the memory requirements for running LDpred2 for optimal speed?

**Comment by privefl** [comment]
For optimal speed, you need to be able to store the full SFBM correlation matrix in memory (30-35GB for HM3 variants).
Therefore, you should be fine specifying e.g. 50 GB.
It is easy to see if you read from disk -> when workers are not at 100% CPU after a few minutes.

But usually you have nodes with ~125GB RAM for 15 cores; why not just requesting 125 (or 250) GB?

**Comment by opain** [comment]
Hello, just to add, I found 60G ram was required to achieve 100% CPU on workers when using HapMap3 SNPs and 10 cores. I tried using 50G but often 100% CPU was not achieved and analysis took up to 5 times longer than with 60G. Previously I did not know how to check CPU usage of workers, and found this website's "How to check resource utilization for running jobs?" section useful: https://kb.northwestern.edu/page.php?id=81074

**Comment by Sabor117** [comment]
Hi Florian,

Apologies for necro-ing an old thread but it seems fairly relevant to me (and was also the first Google result when I searched for "ldpred2 memory requirements").

I am trying to run LDpred2 with the HapMap3+ SNPs using a reference panel of a custom subset of 30k white British individuals from UKB.

While I was able to get this to work when I ran the analysis chromosome-by-chromosome, I understand that you guys recommend running genome-wide and so I've been trying to run that. However, I repeatedly am getting SLURM memory errors with this.

```
Process 1781495 level 1 thread 008 affinity 0-11
Process 1781495 level 1 thread 009 affinity 0-11
Process 1781495 level 1 thread 010 affinity 0-11
slurmstepd: error: StepId=24468568.batch exceeded memory limit (257759014912 > 257698037760), being killed
slurmstepd: error: Exceeded job memory limit
slurmstepd: error: *** JOB 24468568 ON r06c60 CANCELLED AT 2024-11-27T12:02:42 ***
```

This was with a job using 12 cores with 20 GB of RAM each, meaning 240 GB of memory in total. This is obviously a pretty hefty amount of memory and STILL isn't enough.

I am now trying 18 cores of 20 GB of RAM (which is nearing the max memory limit for this form of job submission on our HPC actually).

However, based on the discussion here, is it possible that I would have more luck running this if I used fewer cores with higher memory? E.g. 6 cores with 60 GB of RAM each? Even if this uses a similar amount of memory in total, would it actually potentially work better because of LDpred2 using ~50 GB file sizes for the SFBM matrices?

**Comment by privefl** [comment]
- What is the size of the sfbm .sbk file you use?
- What is the SLURM command you use to ask for resources?

**Comment by Sabor117** [comment]
The relevant SLURM commands are:

```
#SBATCH --time=3-00:00:00
#SBATCH --ntasks=18 # Previously 12
#SBATCH --mem-per-cpu=20G
```

Each version of this job (because it is submitted as an array) creates a 41 GB .bk file.

**Comment by privefl** [comment]
I think you should try using shared memory; you can look at what I use [here](https://github.com/privefl/paper-ldpred2/blob/c7abe0109db6fc388a5958dd6fc89289cf6febfb/batchtools.slurm.tmpl#L4-L6).

For the size of the file, you are talking about the .sbk file, right?
When using the LD ref I provide for HM3+ and the compact format, I think it takes arounds 30GB.
In such case, you should be fine with e.g. 60 GB.

**Comment by Sabor117** [comment]
Ah, so if one uses `mem` instead of `mem-per-cpu` it might work a little better? There might be better sharing of memory between the CPUs? I'll give that a try next if this current attempt doesn't work.

Also, actually, no? The script seems to be producing .bk files. Not .sbk. Is that an issue?

**Comment by privefl** [comment]
- Yes, you should try this instead (and `--ntasks=1 --cpus-per-task=<ncores>`).

- `corr$sbk` should be a .sbk file, right?

**Comment by Sabor117** [comment]
Right, I'll give that a go. The version I had submitted over the weekend (from above) ran out of memory again while running.

Hmm. So I don't actually know what that is within the R environment. Can I confirm that `corr` here is the output of `snp_cor()` or is it the output of `as_SFBM()`?

At the very least the temp files which are saved in the `tmpdir` when it crashes always seem to be just .bk files.

**Comment by privefl** [comment]
The output of as_SFBM.
Also, do not put large files in the tmpdir.

**Comment by Sabor117** [comment]
I'll put a check into the script to see what happens at that stage. I'm now starting to wonder though if that's the part it's running out of memory.

Also, just to be clear, I haven't been using the default home tmpdir. I define a specific location in my project directories for temporary files for presumably the reason you say to not store large files there.

**Comment by privefl** [comment]
If that’s not the default tempdir, but another directory in your project, that’s fine.

**Comment by Sabor117** [comment]
Okay, so just to follow-up on this: it seems like @privefl's fix worked here (at least technically). By using just one core with >300 GB memory the script has been able to keep running (compared with multiple cores each with only 20 GB of memory each, which caused the script to crash after running out of memory).

I may make a follow-up issue to this though because the trade-off has been that while it hasn't crashed, it also has been running for >3 days (and has been running the `snp_cor` command for basically that entire time). And I don't know if that's expected behaviour.

**Comment by privefl** [comment]
I think there are issues here about long running times for `snp_cor()`; try to have a look at those for guidance.
