### ISSUE TITLE
Error in snp_cor for only some of the chromosomes

### ISSUE THREAD

**Issue by bbitarello** [privefl/bigsnpr#173]
Hi Florian, 

I am using bignspr version 1.6.1

I am running snp_cor to make LD matrices to run ldpred2 following your script. Most chromosomes run fine except 1,2,3,5, and 6 (humans). I run this code (which, as I said, works for most chromosomes):

`cat(paste0('Begin LD corr calculations for chromosome', chr, '\n'))
ind.chr <- which(CHR == chr)
runonce::save_run(
snp_cor(
        G, ind.row = ind.val, ind.col = ind.chr,
        alpha = 1, infos.pos = POS2[ind.chr], size = 3 / 1000,
        ncores = NCORES
        ),
file = paste0("tmp-dir/corr/chr", chr,"_",dt,".rds")
)`

and  get this error after a long run for chrs 1,2,3,5,6:

Error in validityMethod(as(object, superClass)) :
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:522
Calls: <Anonymous> ... validObject -> anyStrings -> isTRUE -> validityMethod

I've tried allocating more than the usual 128G. I first increased to 264G and then 300 G.

I've seen this mentioned in other posts but didn't find a solution.
Ideas?

**Comment by privefl** [comment]
You are trying to use much more variants than the 1M HM3 variants, aren't you?

Note that this issue "long vectors not supported yet" has been reported in 3 other issues here.
To summarize:
- you cannot have too many non-zero elements in the sparse Matrix because of some current R limitation
- even if you could, this would make LDpred2 very time and memory consuming (because it is quadratic with number of variants)
- therefore you should restrict to HapMap3 variants as recommended for now

I'm slowly looking at how to best include more variants, and if it would really be useful in terms of increased prediction. For now, phenotypes for which this is useful are not the majority.

If you really want to use more variants, you could try thresholding on MAF  (at e.g. 2% or 5%) and running some clumping (e.g. excluding r2 > 0.95 within 0.5 cM) to make sure you don't have more than 200-300K variants for a given chromosome.

**Comment by bbitarello** [comment]
Hi Florian,
I have been using only HapMap3 SNPs. 
However, I realized that there was an issue with my snp_asGeneticPos run (I modified it slightly locally to handle hg38 map files in beagle format, which is what I have) and it wasn't making the genetic distances correctly. I've fixed it now so I will try to run again and I will report back on how it goes. Thank you

**Comment by privefl** [comment]
Any update on this?

**Comment by bbitarello** [comment]
Yes, this was resolved.
