### ISSUE TITLE
Project a dataset according to 1K genome

### ISSUE THREAD

**Issue by carmaj** [privefl/bigsnpr#197]
Dear Florian,

in order to project a target dataset on the PC space derived from 1K genome is it possible to use the 
"bed_projectSelfPCA" function from bigsnpr package?

where obj.bed is an object derived by the mapping of the bed including both the samples used to derive PC (i.e., 1K genome) and the target cohort.

So the pipeline could be:
1. merge QC-target data with QC-1K genome (https://figshare.com/articles/dataset/1000_genomes_phase_3_files_with_SNPs_in_common_with_HapMap3/9208979/3)
2. potential outliers/relatedness QC
3. compute PC considering only 1K genome data using the function "bed_autoSVD" and filtering with ind.row only samples from the 1K genome
4. project the target samples in the derived PC space using the function "bed_projectSelfPCA" providing as ind.row only samples from the target dataset (i.e., not used to compute the PC)

is this correct?

Best,
Carlo

**Comment by privefl** [comment]
`bed_projectSelfPCA()` is used to project from the same data, e.g. the related individuals that were removed before computing PCA, so that you get some PC scores for everyone.

You need to use `bed_projectPCA()` to project one dataset onto the PCA space of another one. You can find some example code at https://github.com/privefl/paper-ancestry-matching/tree/master/code.

**Comment by privefl** [comment]
Any update on this?
