### ISSUE TITLE
Delta parameter in lassosum2

### ISSUE THREAD

**Issue by Jingning-Zhang** [privefl/bigsnpr#245]
Hi Dr. Florian Privé, 

I noticed in the tutorial (https://privefl.github.io/bigsnpr-extdoc/polygenic-scores-pgs.html#exercises-ldpred2-and-lassosum2) the parameter s was removed and a new delta was introduced. However, I searched in the paper https://www.biorxiv.org/content/10.1101/2021.03.29.437510v1.full.pdf but didn't find the definition of the delta.  

We analyzed many traits and summarized the trend of tuning parameters based on s. So to make the analysis consistent, we want to transform the delta back to s if possible. Is there a **one-to-one transformation** of s and delta? Could you please give the **definition/formula** of delta? Anyway, a formal definition of the delta is always good to know.

Thank you very much in advance!

**Comment by privefl** [comment]
delta is the L2-regularization hyper-parameter (from the documentation of the function); this is also called lambda2 sometimes. I need to update the preprint (you can already find the new paragraph describing lassosum2 at https://github.com/privefl/paper-misspec/blob/main/paper/paper-misspec.tex#L228), but I have not finished the new version yet. And it will likely still take a bit of time.

I don't think there is a one-to-one transformation between s and delta because it also depends on the L1-reg param lambda.

**Comment by Jingning-Zhang** [comment]
Thanks Dr. Prive!
