### ISSUE TITLE
LDpred2-auto using subset of variants

### ISSUE THREAD

**Issue by jelman** [privefl/bigsnpr#246]
I am interested in calculating PRS using only a subset of SNPs from the sumstats and was wondering what the recommended approach would be. Should filtering for this subset be performed at the beginning when matching SNPs between sumstats and genotype? Alternatively, I could run snp_ldpred2_auto on the full sumstats and filter for snps of interest when predicting scores with big_prodMat. Would the beta estimates produced by ldpred differ between these two substantially?

Thanks in advance for your help and for the excellent tool!
Jeremy

**Comment by privefl** [comment]
You should filter before. 
The problem is, if you include other SNPs in LD with the ones you're interested in, the signal might go to them, and you will lose it when filtering in the end.

However, if you're problem is more that you want to assess the prediction per chromosome, you could compute LDpred2 genome-wide and get one prediction per chromosome (as the SNPs on different chromosomes should be independent).

**Comment by jelman** [comment]
Ah, that makes sense. Thank you for the quick reply!
