### ISSUE TITLE
manually construct mhtest object to use snp_gc/snp_qq functions

### ISSUE THREAD

**Issue by 229668880** [privefl/bigsnpr#276]
My current GWAS result is very inflated, so I am trying to do genomic control. I have GWAS summary statistics from other packages or software. 
But snp_gc and snp_qq take mhtest object as an input. How can I manually construct mhtest object?

**Comment by privefl** [comment]
A few examples:
- https://github.com/privefl/bigsnpr/blob/master/R/MAX3.R#L103-L106
- https://github.com/privefl/bigstatsr/blob/master/R/univLinReg.R#L61-L64
- https://github.com/privefl/bigstatsr/blob/master/R/univLogReg.R#L111-L114

What you need is the data.frame with `$score` and then the two functions to compute the log10(p-values).

This is maybe a bit complicated for your need. Otherwise, you can simply adapt the code for genomic control for your need.

**Comment by 229668880** [comment]
Thanks. I made it.
