### ISSUE TITLE
LassoSum divergence

### ISSUE THREAD

**Issue by jordanero** [privefl/bigsnpr#302]
Hi Florian,

Do you understand why LassoSum2 diverges under some conditions? In Mak et al. 2017 Genetic Epi, he says the LassoSum loss function is convex, and thus doesn't suffer from problems of nonconvergence. Does the reparameterization in Prive et al. 2021 BioRxiv cause the loss function to lose its convexity? 

Thanks for all the work you've poured into bignspr. It's made my life way easier. 
Jordan

**Comment by privefl** [comment]
The problem is that it is not a convex problem anymore when the correlation matrix is misspecified (which is always the case).
This is why you need regularization, and especially the L2 regularization (the 's' parameter in lassosum and 'delta' parameter in lassosum2).
Under strong misspecification, you would need stronger regularization. 
For example, see these curves from [this preprint](https://doi.org/10.1101/2021.03.29.437510):
[lassosum2-misN.pdf](https://github.com/privefl/bigsnpr/files/7948773/lassosum2-misN.pdf)
For example, when delta = 3, the L2 reg is so strong that all model converge; however, when delta = 0.001, if lambda (L1-reg) is not large enough, then the model diverges (then you don't see the corresponding point on these curves).

**Comment by jordanero** [comment]
That's super helpful. Thanks a lot.
