### ISSUE TITLE
Some questions of using PCA

### ISSUE THREAD

**Issue by garyzhubc** [privefl/bigsnpr#306]
Suppose I have an object `obj.svd` from `big_SVD`

If I want to select the top SNPs that are positively contributing to the first principal component, shall I do:

```
 tail(order(obj.svd$v[,1]), 100)
```

If I want to plot the samples in their first two principal components, shall I do:

```
ggplot() + geom_point(aes(x=obj.svd[,1],y=obj.svd$u[,2]))
```

**Comment by privefl** [comment]
1. Yes, I guess, but remember that PCs are up to the sign, so that I don't think it makes sense to look only at top positive or top negative (usually, it's more top squared).

2. `plot(obj.svd, type = "scores")`; please have a look at the tutorials on PCA, and the documentation (especially the examples).

**Comment by garyzhubc** [comment]
So I used `plot(obj.svd, type = "scores")` but it looks like I'm getting a plot that's unusually cluttered for a dataset of whole genome with 600 or so samples. 
![image](https://user-images.githubusercontent.com/30366447/152045997-f6a3314b-c8ce-4334-8f25-719a965c51f1.png)

**Comment by privefl** [comment]
Please have a look at the tutorials at https://privefl.github.io/bigsnpr/.

You should probably use `snp_autoSVD()` instead of `big_SVD()`.

**Comment by garyzhubc** [comment]
`snp_autoSVD()` worked
