### ISSUE TITLE
Clumping with LD matrix directly

### ISSUE THREAD

**Issue by jordanero** [privefl/bigsnpr#316]
Hello,

Is there a way to clump using an LD matrix loaded as an SFBM? This would be useful when one doesn't have access to the raw genotype data. 

Thanks!

**Comment by privefl** [comment]
That is a good question. I thought about implementing this multiple times; that would be relatively easy I think.

The problem is more: does it make sense to implement this?
Usually we provide these LD references restricting to 1M HapMap3 variants.
Does it make sense to run C+T by restricting on HapMap3 variants? I don't think so.

Moreover, I don't think you need a very large LD ref for C+T, and usually you need a validation data to tune all the hyper-parameters of C+T, so I think you should use that validation data to run the clumping.

**Comment by jordanero** [comment]
I'm not sure I understand. Why wouldn't it make sense to run C+T after restricting to HapMap3 variants?

I'm hoping to be able to use a larger SNP set than HapMap3 and clump outside of a traditional clumping and thresholding PRS procedure. Specifically, I want to use clumping to make a SNP set that is larger than HapMap3, but with less LD (to avoid convergence issues for a lassoSum variant).

**Comment by privefl** [comment]
Sometimes, you can capture much more variance by using SNPs outside of HM3:

![zoom_log_lipoA](https://user-images.githubusercontent.com/11161036/155027289-4cf90187-6d0e-4362-9e5a-15853d1119f3.png)

**Comment by privefl** [comment]
So, I think the current functions for clumping based on individual-level data should be used.

Feel free to comment if someone strongly disagrees.
