### ISSUE TITLE
The estimated beta is all NA when using the function snp_ldpred2_grid()

### ISSUE THREAD

**Issue by siawhui** [privefl/bigsnpr#345]
Hi,

I am trying to calculate the polygenic score of a binary trait using LDpred2. While using infinitesimal model and automatic model, I managed to get the estimated beta. However, the estimated beta in grid model (`snp_ldpred2_grid`) is all NA.

I have removed the rare variants (MAF < 0.05) and used `snp_match()` for flipping of variants. 

Here is the code i used for `snp_ldpred2_grid`:
```
ldsc <- with(df_beta, snp_ldsc(ld, length(ld), chi2 = (beta / beta_se)^2,
                                sample_size = n_eff, blocks = NULL))
h2_est <- ldsc[["h2"]]
h2_seq <- round(h2_est * c(0.3, 0.7, 1, 1.4), 4)
p_seq <- signif(seq_log(1e-8, 1, length.out = 21), 2)
params <- expand.grid(p = p_seq, h2 = h2_seq, sparse = TRUE)
beta_grid <- snp_ldpred2_grid(corr, df_beta, params, ncores = NCORES)
```

Best,
Siaw

**Comment by privefl** [comment]
This is explained in the tutorial and the documentation; NAs correspond to model that diverged (certainly because they were too far from the right model).
This should be the case for a few models/columns only just choose the best model from the ones that did not diverge.

Also, start the sequence of 'p' at 1e-5, not 1e-8.
