### ISSUE TITLE
Imputed data with HapMap3+ reference data 

### ISSUE THREAD

**Issue by Janina24** [privefl/bigsnpr#388]
Hi Dr. Privé, 

I´m not sure if Iám right when running LDPred2 using imputed data:

- matching imputed data, summary stats and HapMap3+ variants
- build correlation matrix on basis of LD blocks provided for HapMap3+ variants 
or should I use here instead my own (HRC) imputed genotypes (>2,00 individuals)  to build the correlation matrix?

**Comment by privefl** [comment]
So, your question is whether you should use the precomputed LD or just recompute the LD from your data?
If the summary statistics are from European individuals, I would just recommend using the precomputed LD provided.
Otherwise, if you have enough individuals, you could recompute the LD + make the LD blocks (you can use the code from the inference paper as model).

**Comment by Janina24** [comment]
Ok, thanks.
I was just wondering that the correlation was extremly low in the auto model when using imputed data.

**Comment by privefl** [comment]
Which correlation?

**Comment by Janina24** [comment]
pcor(pred_auto, y)

**Comment by privefl** [comment]
Do you expect it to be large? 
What are h2, p, and n_eff?
Also, could you report the `range` of all chains?

**Comment by Janina24** [comment]
It was lower than the pcor when using not imputed genotype data

**Comment by privefl** [comment]
Any update on this?
