### ISSUE TITLE
snp_grid_PRS dimension mismatch

### ISSUE THREAD

**Issue by kulmsc** [privefl/bigsnpr#39]
Following along the vignette entitled "Computing polygenic scores using Stacked Clumping and Thresholding (SCT)" everything works until the function snp_grid_PRS.  The problem is mismatched dimensions between the G, bigsnpr object, and the summary statistic betas and pvals.  Specifically, G contains more snps than the summary statistics.  The exact call that is throwing the problem is assert_lengths().  

A temporary fix is to create a new G, although it could be nice and thought worthwhile to point out, that there could be a more definite solution.

**Comment by privefl** [comment]
I'm not sure I follow. 
Can you be more precise on the problem and the error you encounter?

**Comment by kulmsc** [comment]
Sure. The code is as follows:

```
> multi_PRS <- snp_grid_PRS(G, all_keep, beta, lpval, ind.row = ind.train,
 +                           n_thr_lpS = 50, ncores = 4)
 Error: Incompatibility between dimensions.
```

I check the lengths and get:

```
> dim(G)
[1] 129568  66064
> length(beta)
[1] 1349
>
```

Clearly the length of G (66064) is longer than beta (1349) as there are more SNPs than needed in the G object.  There is no automatic way to limit the size of G.

**Comment by privefl** [comment]
So, you're saying that you have summary statistics only for a subset of the columns of `G`?
There are two ways to deal with that.
1. Taking a subset of `G` that corresponds to your summary statistics (e.g. using `big_copy()` or reading a subset in the first place)
2. Getting `all_keep` to correspond to your summary statistics by using the `exclude` (or `groups`) parameter in `snp_grid_clumping()` and fill the other values of `beta` with whatever (because they won't be used).

**Comment by kulmsc** [comment]
big_copy() worked great, thanks!  For other people that might read this, my code was
```
G2 <- big_copy(X=G,ind.row=1:nrow(G),ind.col=which(obj.bigSNP$map$marker.ID %in% info_snp$rsid),backingfile="./subset")
```
then I used G2 in both snp_grid_clumping() and snp_grid_PRS() instead of G.

**Comment by privefl** [comment]
Glad to hear you solved this problem.

Note that you don't need to use `ind.row = 1:nrow(G)` (because it is already the default).
Also note that you might want to use `ind.col = match(info_snp$rsid, obj.bigSNP$map$marker.ID)` to make sure that the order of the columns match the order of the summary statistics.

Thanks for reporting.
