### ISSUE TITLE
Running ldpred2 auto with reference sample

### ISSUE THREAD

**Issue by lm380-r** [privefl/bigsnpr#413]
Dear Dr. Prive,

Would you be able to share an example of running ldpred2 with the newer ld reference panel you provide on your figshare with the PGC schizophrenia summary statistics? 

I have no issues calculating the PRS when I use our in-house data to create the correlation but for some reason, the PRS are massively inflated when I try to create a PRS with the ld reference panel. I have tried various summary statistics and they all have the same issue. I follow the older code you provide (example-with-provided-ldref.R) so I'm not sure what is going on. 

Thank you in advance!

**Comment by privefl** [comment]
What do you mean by "massively inflated"?

**Comment by lm380-r** [comment]
The PRS values range from x10^15 or x10^17

**Comment by privefl** [comment]
Okay, this has been discussed in other issues here, but I'm repeating it here.

You need to:
- update to the latest GitHub version of the package -> you will quickly get NAs instead of these very large values
- make sure to use the robustness parameters (`allow_jump_sign = FALSE, shrink_corr = 0.95`) -> you can even decrease `shrink_corr` to e.g. 0.5 if there is a strong mismatch between the LD and GWAS sumstats
- if the above still does not help, you can additionally use `use_MLE = FALSE` to revert back to some previous sampling strategy that is less flexible but more robust
