### ISSUE TITLE
LDpred2, snp_ldpred2_auto outputs NAs

### ISSUE THREAD

**Issue by lingjoyo** [privefl/bigsnpr#423]
Hallo Florian

I'm testing this guideline for calculating PRS using LDpred2 https://choishingwan.github.io/PRS-Tutorial/ldpred/ 
The inputs are example data provided by the site. The package, bigsnpr, is version 1.12.2.

When I tried to get adjusted beta from the auto model using following codes, the outputs are all NAs. 
`multi_auto <- snp_ldpred2_auto(
  corr,
  df_beta,
  h2_init = h2_est,
  vec_p_init = seq_log(1e-4, 1.0, length.out=20),
  ncores = NCORES,
  sparse = T,verbose = T
)
`
Do you know the reason? How should I solve this problem?

**Comment by lingjoyo** [comment]
There is another problem with calculating heritability (h2) using the function snp_ldsc. I used GWAS of coronary artery disease (CAD) of which heritability was estimated 40%-50% in some paper. But the result from snp_ldsc is only 9%. Do you think it's normal?

**Comment by privefl** [comment]
1. Please use the official up-to-date tutorial: https://privefl.github.io/bigsnpr/articles/LDpred2.html.

2. These are due to divergence issues (as stated in the documentation). Possible solutions at https://github.com/privefl/bigsnpr/issues/416#issuecomment-1487155785.

3. Please open another separated issue for the LDSc heritability estimation.

**Comment by privefl** [comment]
Any update on this?
