### ISSUE TITLE
Error when mapping file: Invalid argument.

### ISSUE THREAD

**Issue by privefl** [privefl/bigsnpr#488]
I do get an error at a later step (and I do not change anything to the original script, besides changing the pathname):

```r
for (chr in 1:22) { 
   cat(chr, ".. ", sep = "")   
   ## indices in 'df_beta'
   ind.chr <- which(df_beta$chr == chr)
   ## indices in 'map_ldref'
   ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
   ## indices in 'corr_chr'
   ind.chr3 <- match(ind.chr2, which(map_ldref$chr == chr))
   
   corr_chr <- readRDS(paste0("ldref_hm3_plus/LD_with_blocks_chr", chr, ".rds"))[ind.chr3, ind.chr3]
   
   if (chr == 1) {
     corr <- as_SFBM(corr_chr, tmp, compact = TRUE)
   } else {
     corr$add_columns(corr_chr, nrow(corr))
   }
 }
```

```
1.. Error: Error when mapping file:
  Invalid argument.
```

This is an error I have never encountered.

Thanks!

Hannae

_Originally posted by @alhannae in https://github.com/privefl/bigsnpr/issues/487#issuecomment-2007336719_

**Comment by alhannae** [comment]
tmp <- tempfile(tmpdir = "tmp-data")

**Comment by privefl** [comment]
Do you have an existing directory called "tmp-data"?

**Comment by alhannae** [comment]
Hi Florian, 

Yes it already existed. But I didn't think anything of it, since other times it never gave an error. I created a new directory and that seemed to fix it.

I further had no problem running the exact code, up to the point where PRS are being calculated.

I attached public-data3 from your other tutorial since I could not find the UKBB data you refer to.
However, I get this error when running the big_prodVec function:

ukb <- snp_attach("tmp-data/public-data3.rds")
G <- ukb$genotypes
map <- dplyr::transmute(ukb$map,
                        chr = as.integer(chromosome), pos = physical.pos,
                        a0 = allele1, a1 = allele2)  
map_pgs <- df_beta[1:4]; map_pgs$beta <- 1
map_pgs2 <- snp_match(map_pgs, map)

pred_auto <- big_prodVec(G, beta_auto * map_pgs2$beta,
                         ind.col = map_pgs2[["_NUM_ID_"]],
                         ncores = NCORES)

Error: Incompatibility between dimensions.
'y.col' and 'ind.col' should have the same length.
In addition: Warning message:
In beta_auto * map_pgs2$beta :
  longer object length is not a multiple of shorter object length

I calculated betas for all the variants in common between sumstats and hapmap. I think that this is why it errors. Is there any way to make this work without restricting to the variants in the test dataset? I would want to have adjusted betas for all the variants (in stead of restricting to the variants in one dataset) so that I then can use them on different datasets without losing any SNPs.

Also, I noticed that in the 'map_pgs' file the beta's are all '1' while in the map_pgs2 (when doing the matching) those beta's convert to '-1'. Is that supposed to happen? 

Thanks again!

Hannae

**Comment by privefl** [comment]
Please 
- close issues when they are resolved, 
- open a new issue if you have a new question,
- format the code properly so that it is easier to read.

**Comment by alhannae** [comment]
Hi Florian, 

I am sorry for the chaos in addressing issues! I am new to github, so I'll take your feedback with me.

I am reopening this issue because I got again the same error as the one above (first one where I compute the correlation matrix). Previously, this error was due to referring to an already existing tmp file. I changed this in the script. I now have no problems running the R script locally on my laptop on a small subset of my data. However, since I am working with big datasets (400.000 individuals), I need to run this on the supercomputer. However, when I try to compute the correlation matrix, I get the following error:

> for (chr in 1:22) {
>      cat(chr, ".. ", sep = "")
>   ind.chr <- which(df_beta$chr == chr)
>   ind.chr2 <- df_beta$`_NUM_ID_`[ind.chr]
>   ind.chr3 <- match(ind.chr2, which(map_ldref$chr == chr))
>   corr_chr <- readRDS(paste0("ldref_hm3_plus/LD_with_blocks_chr", chr, ".rds"))[ind.chr3, ind.chr3]
> 
>   if (chr == 1) {
>     corr <- as_SFBM(corr_chr, tmp, compact = TRUE)
>   } else {
>     corr$add_columns(corr_chr, nrow(corr))
>   }
> }
> 
> 1.. Creating directory "tmp2-data" which didn't exist..
> Error: Error when mapping file:
>   Invalid argument.


Is there something else that I am missing? 

Thanks very much for your help.

Kind regards,

Hannae

**Comment by alhannae** [comment]
Hi Florian,

I am sorry for the chaos in addressing issues! I am new to github, so I'll take your feedback with me.

I am reopening this issue because I got again the same error as the one above (first one where I compute the correlation matrix). Previously, this error was due to referring to an already existing tmp file. I changed this in the script. I now have no problems running the R script locally on my laptop using the toy binary plink data. However, since I am working with big datasets (400.000 individuals), I need to run this on the supercomputer. However, when I try to compute the correlation matrix on my dataset, I get the following error:

> for (chr in 1:22) {
> cat(chr, ".. ", sep = "")
> ind.chr <- which(df_beta$chr == chr)
> ind.chr2 <- df_beta$_NUM_ID_[ind.chr]
> ind.chr3 <- match(ind.chr2, which(map_ldref$chr == chr))
> corr_chr <- readRDS(paste0("ldref_hm3_plus/LD_with_blocks_chr", chr, ".rds"))[ind.chr3, ind.chr3]
> 
> if (chr == 1) {
> corr <- as_SFBM(corr_chr, tmp, compact = TRUE)
> } else {
> corr$add_columns(corr_chr, nrow(corr))
> }
> }
> 
> 1.. Creating directory "tmp2-data" which didn't exist..
> Error: Error when mapping file:
> Invalid argument.

Is there something else that I am missing? If I compare my data to the toy data, then I see that I have no values for genetic distance (all are '0'). But I thought that when using pre-computed ld matrices, that this was not needed?

Thanks very much for your help.

Kind regards,

Hannae
