### ISSUE TITLE
snp_grid_stacking error: 'y.train' should be composed of different values

### ISSUE THREAD

**Issue by Emmylou-G** [privefl/bigsnpr#57]
Thanks for developing this efficient method for PRS. I am trying to go through the SCT with my own dataset. In the stacking step the code `final_mod <- snp_grid_stacking(multi_PRS, y[ind.train], ncores = NCORES, K = 4)` returns this error `'y.train' should be composed of different values` . In my dataset, the `y   <- obj.bigSNP$fam$affection - 1` is all -10. I found that in the testing dataset you provided the y is 0/1 binary values thus big_spLogReg() is used for stacking. In my dataset, does this error return by big_spLinReg()? And what is the potential solution for this problem?

**Comment by privefl** [comment]
You can't use stacking if you don't have any phenotype.

If you just want to compute C+T scores (merging them for all chromosomes), you have to look at the end of the tutorial.

**Comment by Emmylou-G** [comment]
Thanks for the prompt reply. In this way, I am trying to apply SCT with binary traits for which I have an external dataset containing phenotype information. But I am stilling wondering how do you deal with missing data in SCT paper. According to the previous discussion on this website, I know there are two methods: one is removing missing values using external tools. And the other is imputation. I tried set --geno to 0 in PLINK to remove the missing values in my UK Biobank data, but this step seems to remove too many variants. I also tried to use snp_fastImpute with part of my dataset (with about 250,000 variants) which takes some time to compute. I notice there is about 1 million variants in your dataset for SCT, is there any efficient ways to deal with missing values without removing too many variants?

**Comment by privefl** [comment]
We are talking about two different problems here.

Imputation of genotypes is not necessary for UK Biobank as you can directly read dosages data from UKBB BGEN files.
Another solution would be to restrict to e.g. 1% missing values per variant and then using `snp_fastImputeSimple()`.
But this is not the problem you report here, please restrict issues to only one problem.

**The problem here is that the `y` you provide is composed of the same values, which contains no information, which you can't use for neither linear nor logistic regression. 
You should define the phenotype from elsewhere, but be careful to match the indices between `y` and `G`.**

**Comment by privefl** [comment]
Any update on this?

**Comment by Emmylou-G** [comment]
this method works well for the cases stated above and the error about y.train can be solved by modifying .fam file using external phenotype data. Thanks for following.
