### ISSUE TITLE
Basic usage of creation of PRS using package

### ISSUE THREAD

**Issue by Sabor117** [privefl/bigsnpr#60]
I am a bit confused by conflicting differences between your demo for creating polygenic risk scores (PRS) and the list of features of your package (from https://privefl.github.io/bigsnpr/).

The demo instructs users to use the `big_spLogReg()` function for the creation of PRS from a BigSNP object. However, this function is not listed in the feature list of the package, and meanwhile the feature list **does** mention a `snp_PRS()` function for creating PRS'.

I am unsure about the difference between these functions and whether one is superior to the other, or should be used in different circumstances or for creating different results?

**Comment by privefl** [comment]
- big_spLogReg() fits a penalized logistic regression (method based on individual-level data)

- snp_PRS() just outputs some Clumping and Thresholding (C+T) score (method based on summary statistics)

You'll get more information by reading the documenation of these functions and look at the corresponding publications.

**Comment by Sabor117** [comment]
Thanks Florian.

To clarify though: `big_spLogReg()` is actually from the BigStatsR package and not from BigSNPR (hence my confusion when looking through your online documentation for BigSNPR and not being able to find it).

In terms of creating polygenic risk scores from UKBB data, I note that in your paper supplementary materials you use `snp_PRS()`, so I assume my confusion is unwarranted anyway.

I also wanted to ask a basic question about the reading of .bgen files via `snp_readBGEN()`. In your documentation you specify that this is designed to read UKBB files, and I wanted to check whether this was due to the version of the .bgens used or what specifically this means (as we have other datasets which are also in .bgen format)?

**Comment by privefl** [comment]
No need to apologize for any confusion. Documentation could probably be improved. I just do not have time to do it as I would like to.

1/ `big_spLogReg()` is from package bigstatsr because it fits a penalized logistic regression model that could be applied on any matrix, not only genotype matrix from the bigSNP format of package bigsnpr. This is true for other functions as well and it is basically why there are two different packages.

2/ What paper are your talking about where I use `snp_PRS()`? I have 3 papers where I compute PRS (see README).

3/ Function `snp_readBGEN()` has been tested on UKBB files only (as I do not have access to any other BGEN files). So it should work with BGEN files of the same version as UKBB, but might not work with other BGEN versions.

***
PS1: please use bigstatsr and bigsnpr to refer to the packages (there is no uppercase).

PS2: please open a new issue if you have other questions that are not directly related to this one.

**Comment by Sabor117** [comment]
I understand completely.

1. Okay, that makes sense and useful to know.
2. I was specifically referring to https://doi.org/10.1093/bioinformatics/bty185 (the paper introducing bigsnpr and bigstatsr) as in the supplementary section you demonstrate the usage of snp_PRS() as being faster than PRSice. 
3. Okay, so potentially there actually shouldn't be an issue then? I actually don't know what differs between different versions of BGENs anyway so perhaps the package wouldn't have any problems.

As the original question has been answered, I will close this item after this comment. Thanks again.
