### ISSUE TITLE
Few questions about LDpred2 in bigsnpr

### ISSUE THREAD

**Issue by alesss78** [privefl/bigsnpr#80]
Dear Florian,

Thank you for the amazing tools you keep developing,
Now, I am playing with the code of the toy model you provided with LDpred2 paper. 
avaiable at:  https://privefl.github.io/bigsnpr/articles/LDpred2.html

I would have few questions if you don't mind answering.
1) In your example, summary statistics have alleles marked as "a0" and "a1",
Which is the effect allele to which beta refers? "a0" or "a1"?

2) In order to select the best model ( grid of models session), you use scaled coefficient from the logistic regression (mad x coef). You use that because it is more robust that AUC. Can you elaborate more about this point? robust in which sense? why does AUC is less robust?

3) I plan to try LDpred2 in UK Biobank using only a validation dataset (to speed up computation and reduce RAM usage). In your opinion, which would be the optimal criterion to identify the single PRS with higher predictive performances?    

4) For a validation sample of 40k-100k individuals from UK Biobank, how much RAM do you
suggest, taking into account summary statistics of 2 to 6 milions SNPs ?

5) As an altermative to 4) do you think would be a more robust approach to include also a testing set, select the best sparse and non-spase PRS models in validation set based on mad x coef criterion,  and than select the best among these two based on the AUC on the testing set?

6) Real code availability: Since I plan to try LDpred in UK Biobank on other diseases, I would like to know if it is possible to ask you to share some real code example?  For instance a R script you used to generate one of the PRS reported in LDpred2 paper (e.g., CAD or prostate cancer).

Thank you in advance for your time,

Best

Alessandro

**Comment by privefl** [comment]
Thanks for your feedback and interest in the package.

1) I believe it is a1 the alternative alleles that you need to multiply from. Anyway, some software do not seem to be consistent on this as sometimes we need to revert the effects of prediction.

2) The main problem is that we are combining 22 scores that can have a very different scaling. For e.g. PRCA, scores for two of the chromosomes were off (in terms of scaling). The problem is that AUC does not account for any scaling at all, while a GLM model will maximize a likelihood, which is more stable. And we also use the GLM coeff to put all scores from all chromosomes to a common scale.
We will test stacking LDpred models as well, in which case all those problems of scaling will disappear.

3) I'm not sure I get the question. For now, we recommend to follow the tutorial to choose one best model for each chromosome, scale them properly and combine all 22 resulting scores (sum them up). Any other idea would be welcome.

4) If you process each chromosome individually, RAM should not be an issue. We did not tested with 6 millions variants though. And I wonder if it is a good thing at all to use too many variants.

5) What you can do is select for each chromosome (and if sparse) using (mad x coef). And then choose between sparse or not using the combined score. Note that if a value of $p$ close to 1 is chosen, the sparse model would not be very sparse anyway. I think it is okay to have sparse effects for some chromosomes, and not for others.

6) Sorry about that, I usually release the code used in the paper. As the paper is not completely finished yet and the code resides on some secure cluster where it is not easy to get things out, I will release the code only in the next version of the (finished) paper. However, it is not very different from the code of the tutorial.

Hope that helps. Feel free to follow up on some points.

**Comment by privefl** [comment]
Note that I've updated the tutorial to use GLM Z-Scores as the statistic to maximize.
This is approx. proportional to (coef * mad) but should be even more robust.

**Comment by alesss78** [comment]
Thank you very much!
I will try this afternoon with the Z-score!

Have a nice day and thank you again!

Alessandro

Il giorno gio 7 mag 2020 alle ore 11:11 Florian Privé <
notifications@github.com> ha scritto:

**Comment by privefl** [comment]
Actually, RAM can be a problem for LDpred2-inf (which is used in all models for initialization).
I don't know why `Matrix::solve()` is using so much memory but I've found a much better (faster and using less memory) alternative that will be implemented in the next version.

**Comment by YaohuaYangVEC** [comment]
> 
> 
> Actually, RAM can be a problem for LDpred2-inf (which is used in all models for initialization).
> I don't know why `Matrix::solve()` is using so much memory but I've found a much better (faster and using less memory) alternative that will be implemented in the next version.

Hi Florian,

Have you fixed this issue yet? I have this issue too. In my data, I can run ldpred2 for small chromosomes, e.g. 15 (~170K SNPs) - 22 (~70K SNPs). However, I always meet the issue of out of memory for larger chromosome with > 200K SNPs, e.g. chromosome 10 (~300K SNPs). 

Best,
Yaohua

**Comment by privefl** [comment]
If you have the on-disk data format as input, then it should be fine.
But I don't recommend running LDpred2 with several millions variants. I don't think you'll get better predictive performance. And time requirement is quadratric with number of variants.
A new version of the preprint should be uploaded tomorrow and then will be available 1-2 days after on bioRxiv.

**Comment by YaohuaYangVEC** [comment]
Thanks a lot for this prompt response!! I totally agree with your comment that increasing numbers of SNPs will not necessarily lead to a better prediction performance.

There are two ways in my mind to decrease the number of SNPs: (1) use more stringent QC, e.g. imputation R2>0.9(currently I use 0.8), MAF>0.05(currently I use 0.01), (2)only include Hapmap3 SNPs. Which way will you suggest?

Best,
Yaohua

On Jun 21, 2020, at 10:45 AM, Florian Privé <notifications@github.com> wrote:

﻿

If you have the on-disk data format as input, then it should be fine.
But I don't recommend running LDpred2 with several millions variants. I don't think you'll get better predictive performance. And time requirement is quadratric with number of variants.
A new version of the preprint should be uploaded tomorrow and then will be available 1-2 days after on bioRxiv.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fprivefl%2Fbigsnpr%2Fissues%2F80%23issuecomment-647144784&data=02%7C01%7Cyaohua.yang%40vumc.org%7Cd7d93fec63ac40d2e9d208d815fa2c07%7Cef57503014244ed8b83c12c533d879ab%7C0%7C0%7C637283511521254445&sdata=iuzk%2FXrQpLqAKqohYX2oaLMhgKa7%2FqG6rhgj%2BMPpmdE%3D&reserved=0>, or unsubscribe<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMUSAKSVYR236AC73QHLBP3RXYTKZANCNFSM4M2GUSKA&data=02%7C01%7Cyaohua.yang%40vumc.org%7Cd7d93fec63ac40d2e9d208d815fa2c07%7Cef57503014244ed8b83c12c533d879ab%7C0%7C0%7C637283511521264405&sdata=4B4E3%2BJEAm9EvywEbCcKqT6O90CbS1VcKjej%2FyBZz4o%3D&reserved=0>.

[ WARNING : This email came from an external source. Please treat this message with additional caution.]

**Comment by privefl** [comment]
In the new version, we use the HM3 variants used in PRS-CS (HM3 + some QC I believe).

**Comment by YaohuaYangVEC** [comment]
Thanks a lot! Looking forward to the new version and bets wishes for your paper submission!

Yaohua

**Comment by privefl** [comment]
A new version of the preprint is available.

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
