### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by hrafnfaedhir** [privefl/bigsnpr#94]
Hello, I am trying to install the bigsnpr package to use ldpred2.  Everytime I try to compile it, it gives me the error:

`clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Users/cpatterson/Library/R/3.4/library/bigsparser/include" -I"/Users/cpatterson/Library/R/3.4/library/bigstatsr/include" -I"/Users/cpatterson/Library/R/3.4/library/Rcpp/include" -I"/Users/cpatterson/Library/R/3.4/library/RcppArmadillo/include" -I"/Users/cpatterson/Library/R/3.4/library/rmio/include" -I/usr/local/include  -fopenmp -DARMA_DONT_PRINT_OPENMP_WARNING -DARMA_DONT_PRINT_CXX11_WARNING -DARMA_64BIT_WORD=1 -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘bigsnpr’
* removing ‘/Users/cpatterson/Library/R/3.4/library/bigsnpr’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/d5/zvklxm5n5pvfrfdlpf84fd8w0000gn/T//RtmpP10fwI/file171a047ab63b8/bigsnpr_1.4.2.tar.gz' had non-zero exit status`

I understand that clang doesn't support openmp, but I have tried a bunch of different configurations defining the compiler in the makevars file but I can't seem to figure out how to get5 it to use gcc-9 to compile the rest of the program.

Any thoughts would be greatly appreciated.

**Comment by privefl** [comment]
Can you try some of the things in this blog?
https://thecoatlessprofessor.com/programming/cpp/openmp-in-r-on-os-x/

**Comment by privefl** [comment]
I think you basically need to tell R to use gcc instead of clang.

**Comment by vkp3** [comment]
Hi @privefl , I'm having the same issue when I run
`remotes::install_github("privefl/bigsnpr")`, in particular like @hrafnfaedhir, I'm having an issue trying to specify R to use gcc-9 to compile as opposed to macOS clang.

I've tried adding a ~/.R/Makevars defining CC and CXX variables set to be gcc-9 found under /usr/local/bin, but running the above command after restarting R still provides the same issue.

Any help would be appreciated. 
The latest CRAN package is at 1.30, and I'd like to use the newer features.
Thank you

**Comment by privefl** [comment]
I remember having to do that for an old server, but I don't have access to it anymore.
@hrafnfaedhir, were you able to do this?

**Comment by vkp3** [comment]
Reviewing the error posted by the original post above, I realized I actually had a slightly different error - specifically, `ggfortran` wasn't installed in /usr/local/bin, and the flag FLIBS was looking for this. Using HomeBrew, I installed ggfortran into /usr/local/bin and the compilation proceeded without faults.

However, I'm facing a potentially related issue when I run snp_readBed():
`rds <- snp_readBed(bedfile, backingfile = tmpfile)
Error in readbina(bedfile, bigGeno, getCode()) : 
  Wrong magic number. Aborting..`

Would you know why this error might be happening, and if it is related to an issue in compilation?
Looking at the source for `snp_readBed` I suspect the error has to do with the call to `reach.eof <- readbina(bedfile, bigGeno, getCode())` however, I am not able to diagnose it further because I can't find documentation for `readbina`.

**Comment by privefl** [comment]
Could you please open another issue for this?

**Comment by privefl** [comment]
It is on CRAN now but I think you need to wait for them to build the Mac binaries.
Cf. https://cran.r-project.org/web/packages/bigsnpr/index.html.

@hrafnfaedhir can you tell me when you are able to install the package and close the issue?

**Comment by privefl** [comment]
Thank you for using LDpred2. Please note that we now recommend running LDpred2 **genome-wide** instead of per chromosome. The paper (preprint) and tutorial have been updated.
